$schema: /home/ubuntu/code_project/MetaAgent/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: console
  level: info
  path: "./mcp-agent.log"

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
