version: '3.3'
networks:
  jina-network:
    driver: bridge
services:
  executor:
    image: registry.hubble.jina.ai/executors/k7xuf1u1:66fa918e809a763e423342dc
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - executor
    - --host
    - 0.0.0.0
    - --port
    - '8081'
    - --port-monitoring
    - '57158'
    - --uses-metas
    - '{}'
    - --native
    - --workspace
    - /app/.cache/jina
    healthcheck:
      test: jina ping executor 127.0.0.1:8081
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    volumes:
    - /home/lzh/.cache/jina:/app
    networks:
    - jina-network
  gateway:
    image: registry.hubble.jina.ai/executors/k7xuf1u1:66fa918e809a763e423342dc
    entrypoint:
    - jina
    command:
    - gateway
    - --uses
    - GRPCGateway
    - --graph-description
    - '{"executor": ["end-gateway"], "start-gateway": ["executor"]}'
    - --deployments-addresses
    - '{"executor": ["executor:8081"]}'
    - --port
    - '50826'
    - --port-monitoring
    - '51568'
    expose:
    - 50826
    ports:
    - 50826:50826
    healthcheck:
      test: jina ping gateway grpc://127.0.0.1:50826
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    networks:
    - jina-network
