OPENAI_API_BASE: "https://api.openai.com/v1"
OPENAI_API_KEY: "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"
OPENAI_API_MODEL: "gpt-3.5-turbo"
MAX_TOKENS: 1500
RPM: 10

SERPAPI_API_KEY: "8dab4998fa3a8721045e2717465e6689f5dd9a9dd3d365868e99748baa01ab0d"

SD_URL: "YOUR_SD_URL"
SD_T2I_API: "/sdapi/v1/txt2img"