jtype: Flow
with:
  protocol: http
  port: 60066
executors:
- name: start
  py_modules: ./agents/agents_hub.py
  uses: HubStart
- name: multimodal_agent
  uses: /home/lzh/CodeProject/DIMA/metaagent/agents/multi_modal_agent.yml
- name: end
  py_modules: ./agents/agents_hub.py
  uses: HubEnd
